package ua.kpi.training;

import java.util.ArrayList;
import java.util.List;

/**
 * This class represents model object in MVC pattern
 *
 * @author Yurii Krat
 * @version 1.0, 30.10.2016
 */
public class Model {

    /**
     * The value generated by computer
     */
    private int computerValue;

    /**
     * Left bound of the interval
     */
    private int minValue;

    /**
     * Right bound of the interval
     */
    private int maxValue;

    /**
     * List of user's input values
     */
    private List<Integer> userValues;

    /**
     * Default constructor.
     * Creates list object {@link #userValues}
     */
    public Model() {
        userValues = new ArrayList<>();
    }

    /**
     * Returns integer value generated by computer
     * @return computer's generated value
     */
    public int getComputerValue() {
        return computerValue;
    }

    /**
     * Sets integer value generated by computer
     * @param computerValue computer's generated value
     */
    public void setComputerValue(int computerValue) {
        this.computerValue = computerValue;
    }

    /**
     * Returns integer value which is the left bound of the interval
     * @return minimal value of a range
     */
    public int getMinValue() {
        return minValue;
    }

    /**
     * Sets integer value which is the left bound of the interval
     * @param minValue minimal value of a range
     */
    public void setMinValue(int minValue) {
        this.minValue = minValue;
    }

    /**
     * Returns integer value which is the right bound of the interval
     * @return maximal value of a range
     */
    public int getMaxValue() {
        return maxValue;
    }

    /**
     * Sets integer value which is the right bound of the interval
     * @param maxValue maximal value of a range
     */
    public void setMaxValue(int maxValue) {
        this.maxValue = maxValue;
    }

    /**
     * Returns a list of user's game attempts
     * @return list of user's input values
     */
    public List<Integer> getUserValues() {
        return userValues;
    }

    /**
     * Sets a list of user's game attempts
     * @param userValues list of user's input values
     */
    public void setUserValues(List<Integer> userValues) {
        this.userValues = userValues;
    }
}
